
INSERT INTO plans (name, description, max_members, max_devices, max_territories, max_storage_gb, included_modules) VALUES
('Starter',    'Small teams',           5,   5,   10,  5,   ARRAY['dashboard','territories','routes','visits','forms','analytics']),
('Professional','Growing organizations',25,  25,  100, 50,  ARRAY['dashboard','territories','routes','visits','forms','analytics','ai','sync','inventory','workflows','audit']),
('Enterprise', 'Full platform access',  999, 999, 999, 999, ARRAY['dashboard','territories','routes','visits','forms','geospatial','workflows','analytics','ai','sync','permissions','licensing','inventory','audit','iam','households','wash','me_indicators','indicator_dashboard','score_dashboard','semaphore','historical_trends','bulk_import','geographic_hierarchy','i18n','data_governance','diagnostics','humanitarian_taxonomy','projects','indicator_catalog','data_quality','approval_workflow','evidence_management','knowledge_library','tasks','global_search','observatory','ai_analyst','reporting','alerts'])
ON CONFLICT DO NOTHING;

INSERT INTO modules (key, name, description, is_core) VALUES
('dashboard','Dashboard','Operations overview',TRUE),
('territories','Territories','Territory management',FALSE),
('routes','Routes','Route builder',FALSE),
('visits','Visits','Visit tracking',FALSE),
('forms','Forms Engine','Smart form builder',FALSE),
('geospatial','Geospatial Engine','Maps and geometry',FALSE),
('geometry','Geometry','Geometry features',FALSE),
('risk_mapping','Risk Mapping','Risk layers',FALSE),
('workflows','Workflows','Process automation',FALSE),
('analytics','Analytics','Operational analytics',FALSE),
('ai','AI Engine','AI query engine',FALSE),
('inventory','Inventory','Stock management',FALSE),
('households','Households','Household registry',FALSE),
('wash','WASH','Water sanitation hygiene',FALSE),
('me_indicators','M&E Indicators','Indicators catalog',FALSE),
('indicator_dashboard','Indicator Dashboard','KPI dashboard',FALSE),
('score_dashboard','Score Dashboard','Tabulation scores',FALSE),
('semaphore','Semaphore','Traffic light monitoring',FALSE),
('historical_trends','Historical Trends','Trend analysis',FALSE),
('bulk_import','Bulk Import','Data import engine',FALSE),
('geographic_hierarchy','Geographic Hierarchy','Geographic levels',FALSE),
('i18n','Multilingual','Translation management',FALSE),
('data_governance','Data Governance','Retention and policies',FALSE),
('diagnostics','Diagnostics','Diagnostics engine',FALSE),
('humanitarian_taxonomy','Taxonomy','Humanitarian classification',FALSE),
('projects','Projects','Project management',FALSE),
('indicator_catalog','Indicator Catalog','Universal indicator catalog',FALSE),
('data_quality','Data Quality','Quality checks',FALSE),
('approval_workflow','Approvals','Multi-stage approvals',FALSE),
('evidence_management','Evidence','Evidence capture',FALSE),
('knowledge_library','Knowledge','Knowledge base',FALSE),
('tasks','Tasks','Task management',FALSE),
('global_search','Global Search','Cross-platform search',FALSE),
('observatory','Observatory','Territorial observatory',FALSE),
('ai_analyst','AI Analyst','AI analyst assistant',FALSE),
('reporting','Reporting','Report generation',FALSE),
('alerts','Alerts','Alert engine',FALSE),
('sync','Sync Engine','Offline sync',FALSE),
('audit','Audit','Audit logs',FALSE),
('permissions','Permissions','Access control',TRUE),
('licensing','Licensing','License management',TRUE),
('iam','IAM','Identity management',TRUE)
ON CONFLICT (key) DO NOTHING;
