
-- Seed core modules so navigation items appear
INSERT INTO modules (key, name, description, is_active) VALUES
  ('dashboard',             'Dashboard',            'Main dashboard',                  TRUE),
  ('territories',           'Territories',          'Territory management',             TRUE),
  ('routes',                'Routes',               'Route builder',                   TRUE),
  ('visits',                'Visits',               'Visit tracking',                  TRUE),
  ('forms',                 'Forms Engine',         'Form builder and submissions',     TRUE),
  ('geospatial',            'Geospatial',           'Map and spatial tools',           TRUE),
  ('geometry',              'Geometry',             'Geometry features',               TRUE),
  ('risk_mapping',          'Risk Mapping',         'Risk layers',                     TRUE),
  ('workflows',             'Workflows',            'Workflow automation',              TRUE),
  ('analytics',             'Analytics',            'Analytics engine',                TRUE),
  ('ai',                    'AI Engine',            'AI query engine',                 TRUE),
  ('inventory',             'Inventory',            'Inventory management',            TRUE),
  ('households',            'Households',           'Household management',            TRUE),
  ('wash',                  'WASH',                 'WASH indicators',                 TRUE),
  ('me_indicators',         'M&E Indicators',       'Indicator catalog',               TRUE),
  ('indicator_dashboard',   'Indicator Dashboard',  'KPI dashboard',                   TRUE),
  ('score_dashboard',       'Score Dashboard',      'Score visualization',             TRUE),
  ('semaphore',             'Semaphore',            'Traffic-light monitoring',         TRUE),
  ('historical_trends',     'Historical Trends',    'Trend analysis',                  TRUE),
  ('bulk_import',           'Bulk Import',          'Data import tools',               TRUE),
  ('geographic_hierarchy',  'Geography',            'Geographic hierarchy',             TRUE),
  ('i18n',                  'Multilingual',         'Internationalization',             TRUE),
  ('data_governance',       'Data Governance',      'Governance policies',              TRUE),
  ('diagnostics',           'Diagnostics',          'Diagnostic rules',                TRUE),
  ('humanitarian_taxonomy', 'Taxonomy',             'Humanitarian taxonomy',           TRUE),
  ('projects',              'Projects',             'Project management',              TRUE),
  ('indicator_catalog',     'Indicator Catalog',    'Indicator catalog',               TRUE),
  ('data_quality',          'Data Quality',         'Data quality engine',             TRUE),
  ('approval_workflow',     'Approvals',            'Approval workflows',              TRUE),
  ('evidence_management',   'Evidence',             'Evidence management',             TRUE),
  ('knowledge_library',     'Knowledge Library',    'Knowledge base',                  TRUE),
  ('tasks',                 'Tasks',                'Task management',                 TRUE),
  ('global_search',         'Global Search',        'Search',                          TRUE),
  ('observatory',           'Observatory',          'Territorial observatory',          TRUE),
  ('ai_analyst',            'AI Analyst',           'AI analysis',                     TRUE),
  ('sync',                  'Sync',                 'Offline sync',                    TRUE),
  ('audit',                 'Audit',                'Audit logs',                      TRUE)
ON CONFLICT (key) DO NOTHING;
